---
  - name: Install web packages
    apt:
      state=latest
      name={{item}}
    with_items:
      - php5
      - git
      - libapache2-mod-php5 
      - apache2

  - name: Apache service up
    service: name=apache2 state=started enabled=yes

  - name: Creates the index.php file
    template: src=index.php.j2 dest=/var/www/html/index.php

  - name: Creates the phpinfo.php file
    template: src=phpinfo.php.j2 dest=/var/www/html/phpinfo.php

  - name: Mod rewrite
    command: a2enmod rewrite

  - name: Template custom.conf    
    template: src=custom.conf.j2 dest=/etc/apache2/conf-available/custom.conf
    
  - name: A2enconf custom.conf
    command: a2enconf custom.conf
    notify:
      - restart apache2
